version: "2.1"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 10
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro