version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro